services:
  postgres:
    image: postgres:16.1
    ports:
      - '${DOCKER_DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: $DOCKER_DATABASE_NAME
      POSTGRES_USER: $DOCKER_DATABASE_USERNAME
      POSTGRES_PASSWORD: $DOCKER_DATABASE_PASSWORD

  minio:
    image: 'minio/minio:latest'
    ports:
      - '${DOCKER_FORWARD_MINIO_PORT:-9000}:9000'
      - '${DOCKER_FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":${FORWARD_MINIO_CONSOLE_PORT:-9090}"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:${FORWARD_MINIO_PORT:-9000} root password;
      /usr/bin/mc admin user add myminio $S3_ACCESS_KEY_ID $S3_SECRET_ACCESS_KEY;
      /usr/bin/mc admin policy attach myminio readwrite --user $S3_ACCESS_KEY_ID;
      /usr/bin/mc mb myminio/$S3_BUCKET_NAME;
      /usr/bin/mc anonymous set public myminio/$S3_BUCKET_NAME;
      exit 0;
      "

# use docker compose down --volumes to remove volumes declared in this file
volumes:
  minio:
    driver: local
